# deployment
host: 0.0.0.0
port: 4000
plugins:
  - jekyll-seo-tag
# Site settings
title: mwtndmik Blog
description: "A blog about mwtndmik"
baseurl: "" # for test: remove string '/space-jekyll-templa' to ''
url: "https://mwtndmik.github.io" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.githu.io'
# User settings
username: mwtndmik
user_title: mwtndmik
email: kazuki.sugiyam@gmail.com
twitter_username: mwtndmik
github_username:  mwtndmik
facebook_username: Kazuk.Sugiyam
scrapbox_username: mwtndmik
profile_picture: /assets/img/basic/icon.png

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: home
    url: /
  - title: my posts
    url: /posts
  - title: series
    url: /series
  - title: tags
    url: /tags
  - title: about me
    url: /about
# projects in header index
projects:
  - name: member of "NAFT Nagoya University Aerospace and Flight Technologies"
    url: http://naft.space
# skill_lang in about me
language:
  - name: Kotlin
  - name: TypeScript
  - name: Python
  - name: C
  - name: Scheme
#skill_field in about me
field:
  - name: Blockchain / CryptoCurrency
  - name: Embedded software
  - name: Android
  - name: 3D CAD modeling
#belong in about me
belong:
  - name: Electronic-Mechanical Engineering Course, Department of Mechanical and Aerospace Engineering, School of Engineering, Nagoya University
    url: http://www.nuem.nagoya-u.ac.jp/index.html
  - name: NAFT Nagoya University Aerospace and Flight Technologies
    url: https://naft.space
#services in about me
service:
  - name: Original BTC Address Generator
    url: https://originaladdress.net
    content: You can generate Bitcoin(BTC) address which start with the string you like (called vanity address) on the browser.<br>e.g. Btc → 1BtcCUhM...KyFT15
#awards in about me
award:
  - name: 2018/03  GUNMA PROGRAMMING AWARD 2018 application finalist
    url: https://www.gp-award.jp/final-stage-2018.php
    content: developped "μTCAS", which is "small, light and inexpensive" Traffic alert and Collision Avoidance System for Drone
  - name: 2018/08  Yenom BitcoinHacathon Yenom award
    url: https://www.neweconomy.jp/posts/22873/2#入賞チーム
    content: suggested Android application "sumo", which is a diet application using BitcoinCash and incentive management
  - name: 2019/03  GUNMA PROGRAMMING AWARD 2019 application finalist
    url: https://github.com/mwtndmik/LEthRoom
    content: developped server less P2P real estate lease application "LEthRoom" using ETH blockchain.
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
